#pliki wykorzystywane przy kompilacji
FILEASM32OBJ=
FILEASM64OBJ=
FILECOBJ=\
    src/psmgr/psmgr.o\
    src/database/database.o\
    src/svc_kernel/svc_lock.o\
    src/svc_kernel/svc_log.o\
    src/svc_kernel/svc_kernel.o\
    src/main.o

#plik wynikowy
OUTFILE=niuchacz.out