ARCH=64
DEBUG=0
DEBUG_LEVEL=-g

#Pakiety kompilacyjne wraz z ich konfiguracją
ASM=nasm
LD=gcc
CC=gcc

#Library configuration
SQLLITE_LIB=sqlite/.libs/libsqlite3.so
LIBALGORITHMS_LIB=/lib64/libalgorithms.so
LIBALGORITHMS_INCLUDE=libalgorithms/include
SQLLITE_INCLUDE=sqlite
OTHER_LIBS=-lpcap -lssl -lcrypto -lanl -lconfig -L/usr/local/lib -locilib -L/u01/app/oracle/db/12.2.0.1/db_home/lib -lclntsh

#weryfikacja architektury
ifeq ($(DEBUG), 1)
ASMFLAGS=-f elf64 $(DEBUG_LEVEL)
LDFLAGS=-lc -m64 -lpthread -Wall $(DEBUG_LEVEL) $(SQLLITE_LIB) $(LIBALGORITHMS_LIB) $(OTHER_LIBS)
CFLAGS=-c -m64 -Wall -g -I$(SQLLITE_INCLUDE) -I$(LIBALGORITHMS_INCLUDE) $(addprefix -D, $(DEFINES))
else
DEFINES+= DEBUG_MODE
ASMFLAGS=-f elf64
LDFLAGS=-lc -m64 -lpthread -Wall $(SQLLITE_LIB) $(LIBALGORITHMS_LIB) $(OTHER_LIBS)
CFLAGS=-c -m64 -Wall -I$(SQLLITE_INCLUDE) -I$(LIBALGORITHMS_INCLUDE) $(addprefix -D, $(DEFINES))
endif
#konfiguracja budowania
OBJDIR=.
