ARCH=64
DEBUG=0
DEBUG_LEVEL=-g
DEFINES=_GNU_SOURCE
CURRENT_DIR=$(shell pwd)

#Library configuration
ifeq ($(DEBUG), 1)
SQLLITE_LIB=$(CURRENT_DIR)/sqlite/.libs/libsqlite3.so
LIBALGORITHMS_LIB=$(CURRENT_DIR)/libalgorithms/libalgorithms.so
else
SQLLITE_LIB=/usr/local/lib/libsqlite3.so
LIBALGORITHMS_LIB=/lib64/libalgorithms.so
endif
LIBALGORITHMS_INCLUDE=$(CURRENT_DIR)/libalgorithms/include
SQLLITE_INCLUDE=$(CURRENT_DIR)/sqlite
OTHER_LIBS=-lpthread -lpcap -lssl -lcrypto -lanl -lconfig -lsqlite3
#-L/usr/local/lib

#weryfikacja architektury
ifeq ($(DEBUG), 1)
DEFINES+= DEBUG_MODE
ASMFLAGS=-f elf64 $(DEBUG_LEVEL)
LDFLAGS=-lc -m64 -Wall $(DEBUG_LEVEL) $(SQLLITE_LIB) $(LIBALGORITHMS_LIB) $(OTHER_LIBS)
CFLAGS=-c -m64 -Wall -g -I$(SQLLITE_INCLUDE) -I$(LIBALGORITHMS_INCLUDE) $(addprefix -D, $(DEFINES))
else
ASMFLAGS=-f elf64
LDFLAGS=-lc -m64 -Wall $(SQLLITE_LIB) $(LIBALGORITHMS_LIB) $(OTHER_LIBS)
CFLAGS=-c -m64 -Wall -I$(SQLLITE_INCLUDE) -I$(LIBALGORITHMS_INCLUDE) $(addprefix -D, $(DEFINES))
endif

#Pakiety kompilacyjne wraz z ich konfiguracją
ASM=nasm
LD=gcc
CC=gcc

#konfiguracja budowania
OBJDIR=.
