ARCH=64

#Pakiety kompilacyjne wraz z ich konfiguracją
ASM=nasm
LD=gcc
CC=gcc

#Library configuration
SQLLITE_LIB=sqlite/.libs/libsqlite3.so
SQLLITE_INCLUDE=sqlite
OTHER_LIBS=-lpcap -lssl -lcrypto

#weryfikacja architektury
ifeq ($(ARCH),64)
    ASMFLAGS=-f elf64 -g
    LDFLAGS=-lc -m64 -lpthread -Wall -g3 $(SQLLITE_LIB) $(OTHER_LIBS)
    CFLAGS=-c -m64 -Wall -g3 -I$(SQLLITE_INCLUDE)
else
    ASMFLAGS=-f elf32 -g
    LDFLAGS=-lc -m32 -lpthread -Wall -g3 $(SQLLITE_LIB) $(OTHER_LIBS)
    CFLAGS=-c -m32 -Wall -g3 -I$(SQLLITE_INCLUDE)
endif
#konfiguracja budowania
OBJDIR=.