ARCH=64

#Pakiety kompilacyjne wraz z ich konfiguracją
ASM=nasm
LD=gcc
CC=gcc

#weryfikacja architektury
ASMFLAGS=-f elf64 -g
ifeq ($(TESTENABLED),1)
	LDFLAGS=-lc -m64 -Wall -g3 -lm -lpthread
	CFLAGS=-c -m64 -Wall -g3 -D_GNU_SOURCE
else
	LDFLAGS=-lc -m64 -Wall -g3 -lm -shared -lpthread
	CFLAGS=-c -m64 -Wall -g3 -D_GNU_SOURCE -fPIC
endif
#konfiguracja budowania
OBJDIR=.