#Pakiety kompilacyjne wraz z ich konfiguracją
ASM=nasm
LD=gcc
CC=gcc
CURRENT_DIR=$(shell pwd)

LIBALGORITHMS_INCLUDE=$(CURRENT_DIR)/include
LIBALGORITHMS_SRC_INCLUDE=$(CURRENT_DIR)/src

#weryfikacja architektury
LIBS=-lpthread -Wimplicit-function-declaration
INCLUDES=-I$(LIBALGORITHMS_INCLUDE) -I$(LIBALGORITHMS_SRC_INCLUDE)
DEV_LIBS=-lpthread -Wimplicit-function-declaration
DEV_INCLUDES=-I$(LIBALGORITHMS_INCLUDE) -I$(LIBALGORITHMS_SRC_INCLUDE)
#konfiguracja budowania
OBJDIR=.
