// Configuration file for niuchacz multiprocess service

// Service configuration
SVC =
{
    pidFileName = "/run/niuchacz.pid";
};

// Database configuration
DB =
{
    instances = (
        {
            dbName = "DB_LIVE0";
            fileName = "/var/lib/niuchacz/niuchacz_production.db";
            dropOnClose = false;
        },
        {
            dbName = "DB_KRNL0";
            fileName = ":memory:";
            dropOnClose = false;
        }
    );
};

// Scalable execution workers bounds definitions
WORKERS =
{
    min_count = 2; // Default baseline concurrency profiles level
    max_count = 4; // Absolute ceiling boundary to prevent host CPU saturation
};

// Niuchacz core hardware monitoring mappings
niuchacz =
{
    interfaces = ["wlp0s20f0u10"]; 
};