#Pakiety kompilacyjne wraz z ich konfiguracją
ASM=nasm
LD=gcc
CC=gcc

#weryfikacja architektury
ifeq ($(ARCH),64)
    ASMFLAGS=-f elf64
    LDFLAGS=-lc -m64 -lpthread -Wall -g
    CFLAGS=-c -m64 -Wall -g
else
    ASMFLAGS=-f elf32
    LDFLAGS=-lc -m32 -lpthread -Wall
    CFLAGS=-c -m32 -Wall
endif
#konfiguracja budowania
OBJDIR=.