#Pakiety kompilacyjne wraz z ich konfiguracją
ASM=nasm
LD=gcc
CC=gcc

#Library configuration
SQLLITE_LIB=/home/grzegorz/workspace/niuchacz/lib/ext/libsqlite3.so.0.8.6
SQLLITE_INCLUDE=/home/grzegorz/workspace/niuchacz/sqllite
OTHER_LIBS = -lpcap -lssl -lcrypto

#weryfikacja architektury
ifeq ($(ARCH),64)
    ASMFLAGS=-f elf64
    LDFLAGS=-lc -m64 -lpthread -Wall -g $(SQLLITE_LIB) $(OTHER_LIBS)
    CFLAGS=-c -m64 -Wall -I$(SQLLITE_INCLUDE)
else
    ASMFLAGS=-f elf32
    LDFLAGS=-lc -m32 -lpthread -Wall $(SQLLITE_LIB) $(OTHER_LIBS)
    CFLAGS=-c -m32 -Wall -I$(SQLLITE_INCLUDE)
endif
#konfiguracja budowania
OBJDIR=.